### ISSUE TITLE
Cutscenes stutter at 60 fps

### ISSUE THREAD

**Issue by Coldhaz** [ThirteenAG/GTAIV.EFLC.FusionFix#58] opened 2022-11-16 02:12 UTC
For me cutscenes stutter at 60fps.
I tried using 50 fps but nothing really worked.
Will the framerate be better for this fix?

**Comment by mrkillov** [comment] 2023-02-25 02:19
The cutscenes work without stutter when you take out the audio file cutscenes.rpf from pc/audio/sfx. The theory is that the game is trying to sync the game with the audio files which causes the cutscenes to stutter, maybe there is a frame rate that will make the cutscene work smooth, but I'm not sure what what fps to cap it, for my the game had less stuttering at exactly 48 fps, can to this conclusion because usually movies run in 24 fps so I just doubled it to make it run smoother, maybe this will make it run better for you. Give it a try.

**Comment by AndiDink00x** [comment] 2023-06-21 20:12
If someone has an update to this issue please share

**Comment by Prototaxis** [comment] 2023-07-04 10:59
> The cutscenes work without stuttering when you take out the audio file cutscenes.rpf from pc/audio/sfx. The theory is that the game is trying to sync the game with the audio files which cause the cutscenes to stutter, maybe there is a frame rate that will make the cutscene work smooth, but I'm not sure what fps to cap it at, for me the game had less stuttering at exactly 48 fps, came to this conclusion because usually, movies run in 24 fps so I just doubled it to make it run smoother, maybe this will make it run better for you. Give it a try.

You could try 24000/1001 (23.97) FPS and see if it eliminates stutter.

**Comment by AndiDink00x** [comment] 2023-07-04 13:38
> 

Audio files are 32Khz

**Comment by AndiDink00x** [comment] 2023-07-04 13:39
> > The cutscenes work without stuttering when you take out the audio file cutscenes.rpf from pc/audio/sfx. The theory is that the game is trying to sync the game with the audio files which cause the cutscenes to stutter, maybe there is a frame rate that will make the cutscene work smooth, but I'm not sure what fps to cap it at, for me the game had less stuttering at exactly 48 fps, came to this conclusion because usually, movies run in 24 fps so I just doubled it to make it run smoother, maybe this will make it run better for you. Give it a try.
> 
> You could try 48000/1001 (NTSC 23.976*2) FPS and see if it eliminates stutter. What's the cutscenes.spf audio files' sample rate? Depending on the frequency we can calculate an FPS value for the video that will stay in sync with the audio. E.g. 48kHz audio files usually have 46.875 FPS (48000/1024, so 1024 samples per frame).

Audio files on Cutscenes.rpf are sampled on 32Khz

**Comment by Coldhaz** [comment] 2023-07-04 14:07
But how will we do that?

**Comment by mrkillov** [comment] 2023-07-04 14:23
I know there is an audio exported and tool called IVAudioeditor v1, maybe it will let us extract the cutscenes.rpf files and then we can use something like Audacity to covert the audio files into higher khz. But I'm not sure if it possible to import those new audio files back into .rpf file. I got to test this theory out, I'll update you on the conclusion.

**Comment by AndiDink00x** [comment] 2023-07-04 14:44
> I know there is an audio export tool called IVAudioeditor v1, maybe it will let us extract the cutscenes.rpf files and then we can use something like Audacity to covert the audio files into higher khz. But I'm not sure if it possible to import those new audio files back into .rpf file. I got to test this theory out, I'll update you on the conclusion.

You OpenIV for import/export of audio files

**Comment by mrkillov** [comment] 2023-07-04 15:38
> > I know there is an audio export tool called IVAudioeditor v1, maybe it will let us extract the cutscenes.rpf files and then we can use something like Audacity to covert the audio files into higher khz. But I'm not sure if it possible to import those new audio files back into .rpf file. I got to test this theory out, I'll update you on the conclusion.
> 
> Use OpenIV for import/export of audio files, also check the audio file format

I was able to export the audio files and convert them into 48khz and port them back into the game, even if I convert the file above the 48 khz when I import it shows 48 khz anyway, I was able to play the game but when the game is not capped with fps limit, the same issue exists, it stutters, but at when fps is capped at 48 fps the game runs almost perfect, I did not test  46.875 FPS cause my frame limiter don't support fractional fps cap, but I did test 46 fps but it has not difference. 
![image](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/assets/63436403/0d8b7900-e858-4d0b-9cb9-2b1cf48c29e6)

**Comment by AndiDink00x** [comment] 2023-07-04 17:33
@mrkillov But that isnt 60fps

**Comment by Prototaxis** [comment] 2023-07-04 22:56
> @mrkillov But that isnt 60fps
> 
> **EDIT**: i used Andrew's IV audio editor to import my 48khz .wav audio file of GTA's IV intro cutscene but the audio file that this software exports sounds a little bit wrong and it didnt fix the jittering issue neither at 60 nor 48 fps.
> 
> **EDIT**(2): With the original cutscenes.rpf capping the frames on cutscenes at 46.875fps or even at 48 fps quite reduces the jittering compared with the 60 fps cap, but still there is not that 60fps fluidity, i was checking the animations of game's intro at pc/anim/cuts.img with OpenIV and in terms of smoothness the difference is quite huge with the ingame's cutscenes.

Resampling the audio to 48kHz is not a good idea and may very possibly result in quality loss. Preserving quality in such scenarios is not an easy task and shouldn't be done with audacity in any case. I think the objective here should be to find the underlying cause of the jitter, rather than limiting the framerate of the cutscenes.

**Comment by Prototaxis** [comment] 2023-07-04 23:05
> > > The cutscenes work without stuttering when you take out the audio file cutscenes.rpf from pc/audio/sfx. The theory is that the game is trying to sync the game with the audio files which cause the cutscenes to stutter, maybe there is a frame rate that will make the cutscene work smooth, but I'm not sure what fps to cap it at, for me the game had less stuttering at exactly 48 fps, came to this conclusion because usually, movies run in 24 fps so I just doubled it to make it run smoother, maybe this will make it run better for you. Give it a try.
> > 
> > 
> > You could try 48000/1001 (NTSC 23.976*2) FPS and see if it eliminates stutter. What's the cutscenes.spf audio files' sample rate? Depending on the frequency we can calculate an FPS value for the video that will stay in sync with the audio. E.g. 48kHz audio files usually have 46.875 FPS (48000/1024, so 1024 samples per frame).
> 
> Audio files of pc/audio/sfx/cutscenes.rpf are sampled at 32Khz

Could I get the extracted original audio files? I don't have GTA IV installed at the moment.

**Comment by AndiDink00x** [comment] 2023-07-05 09:49
original 32khz .wav file of game's intro cutscene
https://pixeldrain.com/u/Vs7bqfeo

**Comment by ReneSchimmelpfennig** [comment] 2023-07-08 09:31
Has been fixed in ZolikaPatch now, shame that he's not much of a fan of open source...

**Comment by AndiDink00x** [comment] 2023-07-08 09:37
@ReneSchimmelpfennig if thats true thats huge news, i hope @ThirteenAG also makes an effort fixing this issue

**Comment by ThirteenAG** [comment] 2023-07-08 09:40
> @ReneSchimmelpfennig if thats true thats huge news, i hope @ThirteenAG also makes an effort fixing this issue

Why waste time in doing duplicate work?

**Comment by AndiDink00x** [comment] 2023-07-08 09:41
@ThirteenAG because 1. Zolika Patch does not work on steam CE and 2. its not open source i dont trust him 😄

**Comment by ThirteenAG** [comment] 2023-07-08 09:48
> @ThirteenAG because 1. Zolika Patch does not work on steam CE and 2. its not open source i dont trust him 😄

I know, so there's no fix. It doesn't exist. I can also claim I fixed every possible bug in IV, but code is private, and the binary also private.

> EDIT @ThirteenAG also if thats the case why did you import dynamic shadows when Zolika has already done it 😥

I have no clue what he did or does, @Tomasak asked me to restore some shadows that were missing due to ide flags, and it was possible to do due to the same code being used to enable dynamic tree shadows, so we did it, simple as that.

**Comment by ThirteenAG** [comment] 2023-07-08 10:00
I would also like to point out that there's many contributors to this project, and recent updates are only possible thanks to @Parallellines0451, @Tomasak, @robi29, @RaphaelK12, @MagicAl6244225, @Ash_735 and many others. Anyone is free to contribute.

**Comment by Prototaxis** [comment] 2023-07-08 14:48
> @Prototaxis original 32khz .wav file of game's intro cutscene https://pixeldrain.com/u/Vs7bqfeo
@AndiDink00x Thanks. Looking at the file at the moment, the last few seconds are corrupted. Is that a file transfer issue or do you also get the same problem?

**Comment by AndiDink00x** [comment] 2023-07-08 15:09
@Prototaxis No its corrupted from source and other files are good but Zolika's note to this fix is "Fixed jittery camera motion in cutscenes at high framerates " maybe this issue has nothing to do with audio files idk ...

**Comment by Prototaxis** [comment] 2023-07-08 15:12
Well then I don't see why removing the cutscenes audio file would fix the issue.

**Comment by mrkillov** [comment] 2023-07-08 15:15
> Well then I don't see why removing the cutscenes audio file would fix the issue.

What if because the audio files are so big the game is having trouble loading them fast enough on high frame rate,  so removing the files frees up resources to run the cutscenes smoothly, maybe trying to reduce the cutscene audio size will help?

**Comment by Prototaxis** [comment] 2023-07-08 15:26
> > Well then I don't see why removing the cutscenes audio file would fix the issue.
> 
> What if because the audio files are so big the game is having trouble loading them fast enough on high frame rate, so removing the files frees up resources to run the cutscenes smoothly, maybe trying to reduce the cutscene audio size will help?

@mrkillov  Can you confirm that removing the file completely eliminates stutter? Because in that case we assume it's an audio decoding/syncing issue. Otherwise, it's an unrelated performance issue which can be partially solved by freeing up resources, such as those required for the decoding process, so not inherently an audio-related issue.

**Comment by mrkillov** [comment] 2023-07-08 16:01
> > > Well then I don't see why removing the cutscenes audio file would fix the issue.
> > 
> > 
> > What if because the audio files are so big the game is having trouble loading them fast enough on high frame rate, so removing the files frees up resources to run the cutscenes smoothly, maybe trying to reduce the cutscene audio size will help?
> 
> @mrkillov Can you confirm that removing the file completely eliminates stutter? Because in that case we assume it's an audio decoding/syncing issue. Otherwise, it's an unrelated performance issue which can be partially solved by freeing up resources, such as those required for the decoding process, so not inherently an audio-related issue.

Yes I actually I recorded some gameplay without cutscenes audio files being present, the video has audio but dont mind it because I added it afterwards during editing of this video, but this shows an example of how exactly the game would play like without stuttering. https://youtu.be/3Q_e_q7o9Jg so I can confirm that removing cutscenes audio remove stuttering completely.

**Comment by MagicAl6244225** [comment] 2023-07-08 21:54
> > @mrkillov But that isnt 60fps
> > **EDIT**: i used Andrew's IV audio editor to import my 48khz .wav audio file of GTA's IV intro cutscene but the audio file that this software exports sounds a little bit wrong and it didnt fix the jittering issue neither at 60 nor 48 fps.
> > **EDIT**(2): With the original cutscenes.rpf capping the frames on cutscenes at 46.875fps or even at 48 fps quite reduces the jittering compared with the 60 fps cap, but still there is not that 60fps fluidity, i was checking the animations of game's intro at pc/anim/cuts.img with OpenIV and in terms of smoothness the difference is quite huge with the ingame's cutscenes.
> 
> Resampling the audio to 48kHz is not a good idea and may very possibly result in quality loss. Preserving quality in such scenarios is not an easy task and shouldn't be done with Audacity in any case.
> 
> As far as I understand ADPCM, unlike AAC for example, can use arbitrary chunk sizes (sample-per-frame values), but if we assume that its spf value is 1024, then the framerate for 32kHz sample rate is 32000/1024=31.25FPS. In any case, I don't think this will resolve the issue based on your observations.
> 
> I think the objective here should be to find the underlying cause of the jitter, rather than limiting the framerate of the cutscenes.

Does this imply cutscenes shouldn't stutter at 32FPS? Since 48 is 1.5×32, that account for 48 FPS being a relative sweet spot. Looks pretty smooth when I set CutsceneFpsLimit to 64.

**Comment by Prototaxis** [comment] 2023-07-09 01:57
> > > @mrkillov But that isnt 60fps
> > > **EDIT**: i used Andrew's IV audio editor to import my 48khz .wav audio file of GTA's IV intro cutscene but the audio file that this software exports sounds a little bit wrong and it didnt fix the jittering issue neither at 60 nor 48 fps.
> > > **EDIT**(2): With the original cutscenes.rpf capping the frames on cutscenes at 46.875fps or even at 48 fps quite reduces the jittering compared with the 60 fps cap, but still there is not that 60fps fluidity, i was checking the animations of game's intro at pc/anim/cuts.img with OpenIV and in terms of smoothness the difference is quite huge with the ingame's cutscenes.
> > 
> > 
> > Resampling the audio to 48kHz is not a good idea and may very possibly result in quality loss. Preserving quality in such scenarios is not an easy task and shouldn't be done with Audacity in any case.
> > As far as I understand ADPCM, unlike AAC for example, can use arbitrary chunk sizes (sample-per-frame values), but if we assume that its spf value is 1024, then the framerate for 32kHz sample rate is 32000/1024=31.25FPS. In any case, I don't think this will resolve the issue based on your observations.
> > I think the objective here should be to find the underlying cause of the jitter, rather than limiting the framerate of the cutscenes.
> 
> Does this imply cutscenes shouldn't stutter at 32FPS? Since 48 is 1.5×32, that could account for 48 FPS being a relative sweet spot. Looks pretty smooth when I set CutsceneFpsLimit to 64.

I had the same thought. Is it as smooth as when you remove the cutscenes file?

**Comment by mrkillov** [comment] 2023-07-09 02:35
> > > > @mrkillov But that isnt 60fps
> > > > **EDIT**: i used Andrew's IV audio editor to import my 48khz .wav audio file of GTA's IV intro cutscene but the audio file that this software exports sounds a little bit wrong and it didnt fix the jittering issue neither at 60 nor 48 fps.
> > > > **EDIT**(2): With the original cutscenes.rpf capping the frames on cutscenes at 46.875fps or even at 48 fps quite reduces the jittering compared with the 60 fps cap, but still there is not that 60fps fluidity, i was checking the animations of game's intro at pc/anim/cuts.img with OpenIV and in terms of smoothness the difference is quite huge with the ingame's cutscenes.
> > > 
> > > 
> > > Resampling the audio to 48kHz is not a good idea and may very possibly result in quality loss. Preserving quality in such scenarios is not an easy task and shouldn't be done with Audacity in any case.
> > > As far as I understand ADPCM, unlike AAC for example, can use arbitrary chunk sizes (sample-per-frame values), but if we assume that its spf value is 1024, then the framerate for 32kHz sample rate is 32000/1024=31.25FPS. In any case, I don't think this will resolve the issue based on your observations.
> > > I think the objective here should be to find the underlying cause of the jitter, rather than limiting the framerate of the cutscenes.
> > 
> > 
> > Does this imply cutscenes shouldn't stutter at 32FPS? Since 48 is 1.5×32, that could account for 48 FPS being a relative sweet spot. Looks pretty smooth when I set CutsceneFpsLimit to 64.
> 
> I had the same thought. Is it as smooth as when you remove the cutscenes file?

I just recorded a test run of the first mission cutscene side by side comparison at 60fps capped one with sound and one without sound file, clearly one without sound runs way smoother, check it out: https://www.youtube.com/watch?v=SW5d1rUH8b4

**Comment by mrkillov** [comment] 2023-07-09 03:24
I also tested 30 fps capped and game works perfect without stutter with sound but it's not as pleasant as 60 fps.

**Comment by Prototaxis** [comment] 2023-07-09 05:35
> I also tested 30 fps capped and game works perfect without stutter with sound but it's not as pleasant as 60 fps.

I was specifically referring to 64fps with sound vs no sound.

**Comment by Prototaxis** [comment] 2023-07-09 05:36
If audio is indeed what causes this issue, then there's no way to fix it as the decoder is in the engine itself (in the binary) and it's impossible to swap it with a different, more stable decoder.

**Comment by mrkillov** [comment] 2023-07-09 13:01
Well I guess we can reverse engineer the the encrypted code, then we probably could fix this 😄 anybody knows how to read machines code?

**Comment by Coldhaz** [comment] 2023-07-11 03:29
Unfortunately I don't know how to read machine codes.

**Comment by JackSound01** [comment] 2023-09-05 02:10
A friend of mine tried the "zokila's patch" and didn't work , and i tried setting the game at different fps and still stuttering, any fix or fusion fix is going to have an update for that??

**Comment by RecklessGlue540** [comment] 2023-10-06 21:07
From my tests i see that the stuttering also occurs on console. It is a lot more reduced though. The Xbox 360 Version behaves similarly to the PC Version (A LOT smoother) while in the PS3 Version it's completely absent.

> A friend of mine tried the "zokila's patch" and didn't work , and i tried setting the game at different fps and still stuttering

Zolika only fixed the cutscene zooming and claimed to have fixed the camera motion (doesn't really seem to work) and not the actual character / moving objects animation stutter.
Some comparison footage:
PC (1.2.0.59 RGL, Vanilla, VSync Off)
https://streamable.com/d1y6kk

Xbox 360 (Xenia Canary, VSync disabled in config - no differences with it enabled)
https://streamable.com/bp2ggf

PlayStation 3 (RPCS3, VSync disabled, 60FPS Patch, VBlank frequency to 120hz)
https://streamable.com/stlxa7
It may seem smoother in the videos but in reality the stutters are a bit worse. The PS3 Version is still smoother than the other two.

**Comment by RecklessGlue540** [comment] 2023-10-08 13:23
cutscenes.rpf file sizes for each platform are as follows:

PlayStation 3: 448 MB (470,765,568 Bytes)
Xbox 360: 483 MB (507,496,448 Bytes)
PC: 808 MB (847,894,528 Bytes)

That would't explain why there is a difference between the Xbox 360 (Stutter is present) and the PS3 (Stutter not there) since the differences between them in file sizes are very small.

> What if because the audio files are so big the game is having trouble loading them fast enough on high frame rate, so removing the files frees up resources to run the cutscenes smoothly, maybe trying to reduce the cutscene audio size will help?

I don't think the stutters are related to the actual frame rate since you can probably see in the PS3 video above that the frame rate drops heavily when the camera turns around to the city (lower - mid 40s) and it doesn't stutter at all.
Should I also mention that cutscene stutter also occurs in other RAGE games?
RDR1 and GTAV are well known cases already based on this video:

https://www.youtube.com/watch?v=m9QmGxSKZ_4  - minute 9:10 to 9:50

**Comment by Tomasak** [comment] 2023-10-31 13:23
Fixed on 2.0

**Closed by Tomasak** 2023-10-31 13:23 UTC

**Comment by RecklessGlue540** [comment] 2023-10-31 16:36
> Fixed on 2.0

Character animations still aren't as smooth as they should play without the cutscenes.rpf tho. Not for me at least.

**Comment by Undisputed00x** [comment] 2023-10-31 16:39
> > Fixed on 2.0
> 
> Character animations still aren't as smooth as they should play without the cutscenes.rpf tho. Not for me at least.

Despite the improvement i agree that the smoothness is not as it should have been

**Comment by JackSound01** [comment] 2023-10-31 16:39
> > Fixed on 2.0
> 
> Character animations still aren't as smooth as they should play without the cutscenes.rpf tho. Not for me at least. Can anyone else test it?

Really?? Could you upload an example?

**Comment by RecklessGlue540** [comment] 2023-10-31 16:53
Here it is. Looks like the camera pans aren't any better either.
https://streamable.com/4qit6w

Also, when the camera focuses the cook's face (1:21), the room gets a bluish tint? Probably timecycle modifiers related as those had some changes in this update.

**Comment by RecklessGlue540** [comment] 2023-10-31 17:46
I really have no idea what may be causing it.
Another theory:
When you reach a specific time in a cutscene, everything will play flawlessly (regardless of the platform) for a few seconds until it stutters back again.
Those specific durations are reached when the cutscene has to switch it's animation file (since cutscenes are split into sections).
However, in between that time, the audio will still stay in sync (The audio being a single file that's not split into sections).
That still wouldn't explain why short cutscenes (those without sections) still stutter.

**Comment by Undisputed00x** [comment] 2023-10-31 18:21
> I really have no idea what may be causing it. Another theory: When you reach a specific time in a cutscene, everything will play flawlessly (regardless of the platform) for a few seconds until it stutters back again. Those specific durations are reached when the cutscene has to switch it's animation file (since cutscenes are split into sections). However, in between that time, the audio will still stay in sync (The audio being a single file that's not split into sections). That still wouldn't explain why short cutscenes (those without sections) still stutter.

First cutscene sample on YT 60fps: https://www.youtube.com/watch?v=kD_4LtHtpTM

I also notice what @RecklessGlue540 says, but i see that the faster cutscene objects move the more the stutter is visible like the Roman's car on first cutscene. Cutscenes in general feel smoother like in some moments there are 100% smooth (I play on 144hz monitor) but mostly there are visible frames on scenes that seem to be a little off

**Comment by RecklessGlue540** [comment] 2023-10-31 18:32
> I play on 144hz

I thought the stuttering gets more manageable at abysmally high frame rates (Like 200 and up). Doesn't seem like it....

**Comment by RecklessGlue540** [comment] 2023-11-01 12:44
@Tomasak, can you reopen this? As it's in no way fixed...

**Comment by RecklessGlue540** [comment] 2023-11-02 19:20
Alright. To clarify things a little bit more, the supposed fix that ships with the latest version is actually a workaround (It's clearly stated in the source anyway).

Now, I think this workaround basically just detects when the cutscene zooms in and / or stutters and it immediately resets the zoom factor and / or the motion rate the cutscene runs at currently.

I can literally see that when the cutscene camera changes, i see the broken zoom for a split second, then the workaround immediately resets the zoom factor of the camera. Same goes for the stuttering (which in that case only the camera stuttering was fixed, still leaving the characters stuttering about).

**Comment by RecklessGlue540** [comment] 2023-11-02 19:45
From basic testing, it seems like those stutters are also present when running the cutscenes in OpenIV.
However, if you were to cap the frame rate using RivaTuner (which also caps the frame times, very important it seems), the cutscenes are completely smooth. No idea what's up with that...

**Comment by Undisputed00x** [comment] 2023-11-02 19:46
Definitely not a fix but an improvement to this issue, still it should stay open @Tomasak @Coldhaz .

> PlayStation 3 (RPCS3, VSync disabled, 60FPS Patch, VBlank frequency to 120hz) https://streamable.com/stlxa7

This is how cutscenes should have played with this "fix"

**Comment by JackSound01** [comment] 2023-11-02 19:47
> From basic testing, it seems like those stutters are also present when running the cutscenes in OpenIV. However, if you were to cap the frame rate using RivaTuner (which also caps the frame times, very important it seems), the cutscenes are completely smooth. No idea what's up with that...

In Riva at 60fps or 30fps?

**Comment by RecklessGlue540** [comment] 2023-11-02 19:48
> In Riva at 60fps or 30fps?

Any framerate...

**Comment by Undisputed00x** [comment] 2023-11-02 20:23
> From basic testing, it seems like those stutters are also present when running the cutscenes in OpenIV. However, if you were to cap the frame rate using RivaTuner (which also caps the frame times, very important it seems), the cutscenes are completely smooth. No idea what's up with that...

Doesnt work for me, capped also at fractional framerate 59.94 still no improvement

**Comment by RecklessGlue540** [comment] 2023-11-02 20:49
> > From basic testing, it seems like those stutters are also present when running the cutscenes in OpenIV. However, if you were to cap the frame rate using RivaTuner (which also caps the frame times, very important it seems), the cutscenes are completely smooth. No idea what's up with that...
> 
> Doesnt work for me, capped also at fractional framerate 59.94 still no improvement

In OpenIV?

**Comment by Undisputed00x** [comment] 2023-11-02 21:24
@RecklessGlue540  Oh i thought your talking about ingame, in OpenIV animations play buttery smooth without any frames cap

**Comment by RecklessGlue540** [comment] 2023-11-02 21:27
> in OpenIV animations play buttery smooth without any frames cap

Heh, not for me.

**Comment by Undisputed00x** [comment] 2023-11-02 23:09
Again deleted cutscenes.rpf to compare the differences after the 2.0 update and its pretty visible on my 144hz display that FusionFix 2.0 didnt actually fix the issue at all

This is how a fix would look like **(after ofc deleting cutscenes.rpf)**:
https://youtu.be/pCsBb0VEClw
Not sure how much clear the difference can be seen on YT here is the raw vid file:
https://pixeldrain.com/u/RPRn7ACk
It would be even better to check the game yourself by deleting the file on pc\audio\sfx\custcenes.rpf

This is FusionFix 2.0:
https://youtu.be/kD_4LtHtpTM

@Tomasak  @ThirteenAG 
Once again im asking for this issue to be reopened as it should because its clear that the 2.0 update is about an improvement and not a fix in the cutscenes stuttering problem, im not demanding from devs to share their free time on fixing this but at least leave the issue open so it can be visible in a case for a possible future fix.

**Comment by RecklessGlue540** [comment] 2023-11-02 23:34
Best example of how it should look: https://www.youtube.com/watch?v=yltP_dYU3mE
Looks surreal.... : )

**Comment by RecklessGlue540** [comment] 2023-11-03 19:25
Yeah, seems like audio sample rate and file size don't help either. Took me some time reducing the sample rate to 16000hz using Audacity and still it stutters. Used the above cutscene at base. 
Here's the file anyway:  https://www.mediafire.com/file/3ld1uo1ggjo7xsg/ROM3_A/file
Definitely something somewhere else....

**Comment by RecklessGlue540** [comment] 2023-11-09 20:17
Opened another one: https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/issues/246
