### ISSUE TITLE
Incompatibility with DXVK.

### ISSUE THREAD

**Issue by juicermv** [ThirteenAG/GTAIV.EFLC.FusionFix#131] opened 2023-08-13 10:11 UTC
There's an issue with the latest version of DXVK (2.2 at the time of writing), where no resolution above 1200x600 can be selected in the options menu. I've tried to work around this by manually setting the resolution via the launch arguments on Steam but this causes the game to not launch at all. This does not happen without FusionFix installed.

**Comment by ReneSchimmelpfennig** [comment] 2023-08-13 10:41
It's a DXVK bug, you need to put "d3d9.forceAspectRatio = 16:9" in your dxvk.conf in the game folder.
(If you have a 16:9 screen, that is.)

**Comment by juicermv** [comment] 2023-08-13 13:54
Oh okay thanks. Wonder if this can be fixed from the mod's side as well.

**Comment by K0bin** [comment] 2023-08-14 10:09
@ReneSchimmelpfennig It's not a DXVK bug. The game has some hidden logic to filter display modes. No idea how it works or why it does that.

DXVK does expose all display modes to the game and it works fine in every other game.

**Comment by Imflyin2023** [comment] 2023-08-14 22:53
> Oh okay thanks. Wonder if this can be fixed from the mod's side as well.

Hello, can you add the ability to change bloom in the game? I always disable it, because it seems to me that the game looks better without it, bloom is in the visualSettings.dat file in common/data and in TBoGT/common/data, open it with notepad, and you can find these lines
misc.BloomIntensityClamp.HD 10
misc.BloomIntensityClamp.SD 10.00

and so, you just need to change these values 10 and 10.00, you can add this in game in the settings screen.

There is also a misc.BloomIntensityClamp.SD.ps3 5.00 but this is most likely not used in the PC version.

**Comment by Tomasak** [comment] 2023-12-26 14:05
FF was updated in mean time, does this still persist to you? I can select even resolutions higher than monitors with DSR enabled and dxvk installed

**Comment by RecklessGlue540** [comment] 2023-12-26 17:00
> FF was updated in mean time, does this still persist to you? I can select even resolutions higher than monitors with DSR enabled and dxvk installed

Only some GPUs seem to have this issue. For example, my integrated Vega 8 inside my 5700G sees resolutions fine up to 4K.
On my GTX 1060 3GB, nothing higher than 960p can be selected.

Like was said, this thing can be fixed by placing this command inside an empty dxvk.conf:
`# forceAspectRatio only exposes modes with a given aspect ratio. Useful for titles that break if they see ultra-wide.
d3d9.forceAspectRatio = 16:9`

**Comment by Tomasak** [comment] 2023-12-26 17:26
the gtx 1060 is integrated too or dedicated? As im using 1060 6gb dedicated and cant reproduce this issue

**Comment by Tomasak** [comment] 2023-12-26 19:09
idk i have 2 monitors hooked to 1060 and no such issue. Used latest public dxvk (2.3 iirc) without any config applied and it all just works :D

**Comment by RecklessGlue540** [comment] 2023-12-26 19:38
Also: https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/issues/333

This issue also affects refresh rates from what I've seen...
iirc, they're duplicated a few times on that slider even on D3D9, but it needs some testing.

**Comment by SandeMC** [comment] 2023-12-26 20:40
Weird issue. I'm on a dual-monitor desktop setup with a 1650, and on both monitors it recognizes resolutions fine, with 75hz on both. 1080p both. The workaround is to apply -width -height -refreshrate, but I wonder why does it even happen.

**Comment by SlimF** [comment] 2023-12-27 21:33
Sadly the "d3d9.forceAspectRatio" tweak causes the game to crash on start when you've entered 21:9 for ultrawide aspect ratios.

**Comment by ReneSchimmelpfennig** [comment] 2023-12-27 21:43
> Sadly the "d3d9.forceAspectRatio" tweak causes the game to crash on start when you've entered 21:9 for ultrawide aspect ratios.

It works for me, you need to make sure to enter the correct aspect ratio tho, as neither 2560x1080 nor 3440x1440 are exactly 21:9. (2560x1080 has an aspect ratio of 64:27 and 3440x1440 has an aspect ratio of 43:18)

**Comment by SlimF** [comment] 2023-12-28 15:38
> > Sadly the "d3d9.forceAspectRatio" tweak causes the game to crash on start when you've entered 21:9 for ultrawide aspect ratios.
> 
> It works for me, you need to make sure to enter the correct aspect ratio tho, as neither 2560x1080 nor 3440x1440 are exactly 21:9. (2560x1080 has an aspect ratio of 64:27 and 3440x1440 has an aspect ratio of 43:18)

Absolute legend! Working as intended now, even detects DSR resolutions. Thank you so much!

**Comment by Tomasak** [comment] 2023-12-31 11:19
so is this technically resolved?

**Comment by RecklessGlue540** [comment] 2023-12-31 11:30
For me now with a 6700, works fine now.
Still resolutions and refresh rates are duplicated a couple of times, but all get detected.
This could be moved to a new issue in the vanilla issues list.

**Comment by Tomasak** [comment] 2023-12-31 15:41
ye but the duped resolution is fault of dxvk

**Comment by RecklessGlue540** [comment] 2023-12-31 15:44
Maybe. Feel free to close then.

**Closed** 2024-01-01 12:24 UTC
