### ISSUE TITLE
Crash on 'In the Crosshairs' mission in TBoGT

### ISSUE THREAD

**Issue by ZT-1** [ThirteenAG/GTAIV.EFLC.FusionFix#65] opened 2023-03-26 14:47 UTC
I've noticed a consistent crash in the mission 'In the Crosshairs' in TBoGT. I have only fusionfix and dxvk in my game (on latest CE 1.2.0.59). I've also tried disabling all options in hopes that it was a specific one, but I still get a crash even with everything disabled.

Steps to reproduce: It happens in the part after killing the four rooftop snipers. I skip every possible cutscene in the mission (intro and two of the sniper kills included), kill one of the Russians in the back of the chopper, then kill the pilot and keep progressing until at some point after this it crashes.

I did further testing a few times with fusionfix.asi out of my game completely and the mission crashes less frequently.

Another topic describing this crash but they didn't say if they use fusionfix: https://www.speedrun.com/gtatbogt/thread/6tc75

**Comment by ZT-1** [comment] 2023-03-27 09:56
CrashDump of the issue:
[CrashDumps.zip](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/files/11077227/CrashDumps.zip)

**Comment by Tomasak** [comment] 2023-04-09 13:49
I recently 100% tbogt and replayed this mission numerous times to get gold in it without any crash. Try also getting radio downgrader, in case rockstar forgot/messed up some audio file (as i had that along fusion fix) 
http://downgraders.rockstarvision.com/

**Comment by ZT-1** [comment] 2023-04-10 15:51
I definitely always have radio downgrader. Can’t play without it. But yeah, this is still happening to me.

**Comment by barfl00s** [comment] 2023-12-10 16:44
I'm affected by this crash as well, currently using FusionFix 2.2. 
Unfortunately, neither the radio downgrader or the texture mod posted above seem to fix it.
I've noticed that it is extremely hard to replicate consistently, as it happens only under some very specific conditions (time of day, input type, even the weather possibly).

Here's my [CrashDumps](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/files/13628508/CrashDumps.zip) folder.

**Comment by barfl00s** [comment] 2023-12-10 16:45
I'm attaching a [save file](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/files/13628450/TBOGT.Save.File.zip), hopefully it might help other people trigger the crash. 

Try to do the following:

- Unzip the save file in `My Documents\Rockstar Games\GTA IV\Profiles\<your-profile-id>\`
- Load the save, from your menu it should be called **TBoGT - Dropping In**
- Try to get into a taxi cab as fast as you can, select Bulgarin's place and skip the trip
- Start the mission and skip the cutscene, you should still find the taxi waiting outside
- Get inside, skip the trip again to your destination in Little Italy
- The in-game time of the day should be around 6-20 / 6-30 AM at this point, get to the mission marker to initiate the cutscene on the rooftop
- As soon as you get control of your character again, **using an XInput controller**, try and zoom in multiple times with your sniper rifle facing **west**

Unless this bug is hardware specific, this should be the easiest way to replicate it.

**Comment by ThirteenAG** [comment] 2023-12-11 10:54
I can confirm that:
- Crash happens because of the game trying to spawn a car
- Doesn't happen with all sliders set to value "2"

**Comment by Tomasak** [comment] 2023-12-25 16:30
Should be fixed on latest version

**Closed by Tomasak** 2023-12-25 16:30 UTC
