### ISSUE TITLE
[Issue] Cutscenes still stutter after FusionFix 2.0

### ISSUE THREAD

**Issue by RecklessGlue540** [ThirteenAG/GTAIV.EFLC.FusionFix#246] opened 2023-11-09 20:14 UTC
Cutscene stuttering is still present after FF 2.0. Cutscene zooming was indeed fixed, but jitter is still there.
How it should look: https://www.youtube.com/watch?v=yltP_dYU3mE

**Comment by Undisputed00x** [comment] 2023-11-09 20:24
Just for the record removing **cutscenes.rpf** from **GTA IV\pc\audio\sfx** fixes the issue but removes the sounds from game cutscenes

**Comment by lorik-dev** [comment] 2023-11-20 15:24
Cutscenes have major frame pacing issues above 50FPS. You should cap the cutscene frame rate at 50 in GTAIV.EFLC.FusionFix.ini

**Comment by crock8** [comment] 2023-12-19 16:17
I've seen that Zolika patch has a setting that fix that stuff. And i try to turn it on. Game crashed during cuscene. So i removed Fusion, and run with his patch only. Well... And the result was quite good. Cutscenes were smooth as if u delete rpf sound file...

**Comment by RecklessGlue540** [comment] 2023-12-19 16:33
> I've seen that Zolika patch has a setting that fix that stuff. And i try to turn it on. Game crashed during cutscene. So i removed Fusion, and run with his patch only. Well... And the result was quite good. Cutscenes were smooth as if u delete rpf sound file...

I personally didn't see any difference with it. Maybe ZPatch's only works at 200+ framerates as described...
At 60fps, both mods fail to work how they should.
I'm just out of hopes for a real fix at this point.

**Comment by crock8** [comment] 2023-12-19 16:40
> > I've seen that Zolika patch has a setting that fix that stuff. And i try to turn it on. Game crashed during cutscene. So i removed Fusion, and run with his patch only. Well... And the result was quite good. Cutscenes were smooth as if u delete rpf sound file...
> 
> I personally didn't see any difference with it. Maybe ZPatch's only works at 200+ framerates as described... At 60fps, both mods fail to work how they should. I'm just out of hopes for a real fix at this point.

Hah, no, i don't have that much fps. My pc is pretty old. But for me his solution was smoother. But without i can't play without Fusion mod. It's too good to delete it for a few fps in cutscenes

**Comment by RecklessGlue540** [comment] 2023-12-19 16:44
Well, if I can remember right, his was a bit smoother, but definitely not like the PS3 version...
But let's stop with ZPatch. It's FusionFix where focus is on right now.

**Comment by TailsGuy** [comment] 2023-12-22 14:41
I've been messing around with cutscene FPS cap limits and not even 30FPS solves anything here.

**Comment by RecklessGlue540** [comment] 2023-12-22 14:51
> I've been messing around with cutscene FPS cap limits and not even 30FPS solves anything here.

I know. This stutter is present at any framerate.

**Comment by RecklessGlue540** [comment] 2023-12-30 20:01
The issue has been tackled with latest updates. Stutter is still there however. Nowhere near a full fix.
I can confirm it's a bit smoother.

**Comment by JackSound01** [comment] 2023-12-30 20:19
> The issue has been tackled with latest the update. Stutter is still there however. Nowhere near a full fix. I can confirm it's a bit smoother.

Still stutters like the old version..

**Comment by RecklessGlue540** [comment] 2023-12-30 20:28
In some ways...
Maybe because I also upgraded my GPU... (probably Enhanced Sync and other things influence it...)

**Comment by hammerfist11** [comment] 2024-01-07 19:43
Is there any reason it does this? It's quite annoying given how story focused the game is.

**Comment by RecklessGlue540** [comment] 2024-01-07 19:56
> Is there any identified reason it does this? It's quite annoying given how story focused the game is.

Actually not yet. There's countless theories about it in the previous thread tho https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/issues/58

**Comment by ThirteenAG** [comment] 2024-01-15 06:54
[GTAIV.EFLC.FusionFix.zip](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/files/13935790/GTAIV.EFLC.FusionFix.zip)

Can someone test this build for this issue?

**Comment by TailsGuy** [comment] 2024-01-15 07:42
Actively better, this time round it doesn't seem as if the animations are stuttering, rather they're running at a different FPS.

**Comment by ThirteenAG** [comment] 2024-01-15 07:50
Is it something good enough to include in the next release?

**Comment by TailsGuy** [comment] 2024-01-15 07:57
> Is it something good enough to include in the next release?

Hm. Honestly, yeah, go for it. It's a notable improvement. It ain't *completely* fixed but it's satisfactory for now. Needs more research for sure though

**Comment by Undisputed00x** [comment] 2024-01-15 11:31
Its not fixed, just moved cutscenes.rpf away from its folder and compare, its nowhere near to that. Please dont prematurely close this ticket like the #58

**Comment by TailsGuy** [comment] 2024-01-15 12:23
Damn, I must have been mistaken, sorry. It's still in fact stuttery but I figured it wasn't as intense. Maybe it varies on a case by case?

**Comment by TailsGuy** [comment] 2024-01-15 12:23
> Removing cutscenes.rpf doesn't make any difference to me.

Damn, I must have been mistaken, sorry. It's still in fact stuttery but I figured it wasn't as intense. Maybe it varies on a case by case?

**Comment by ThirteenAG** [comment] 2024-01-15 12:24
I have no clue ¯\_(ツ)_/¯

**Comment by Tomasak** [comment] 2024-01-15 12:29
with and without said rpf feels absolutely same https://streamable.com/urj6hs https://streamable.com/4c3cum
(using asi from this issue)

**Comment by Undisputed00x** [comment] 2024-01-15 12:42
> with and without said rpf feels absolutely same https://streamable.com/urj6hs https://streamable.com/4c3cum (using asi from this issue)

Even from your recordings the stuttering is visible

**Comment by RecklessGlue540** [comment] 2024-01-15 13:29
Nope. Still not fixed. The animations do seem smoother a bit... but now, they look like they play flat out at a 30hz smoothness instead of constantly fluctuating...
They still stutter. Will have to try without cutscenes.rpf

**Comment by Tomasak** [comment] 2024-01-15 13:30
> > with and without said rpf feels absolutely same https://streamable.com/urj6hs https://streamable.com/4c3cum (using asi from this issue)
> 
> Even from your recordings the microstuttering is visible

im not arguing that, im only pointing out that removing cutscenes.rpf does nothing

**Comment by RecklessGlue540** [comment] 2024-01-15 13:37
> > > with and without said rpf feels absolutely same https://streamable.com/urj6hs https://streamable.com/4c3cum (using asi from this issue)
> > 
> > 
> > Even from your recordings the microstuttering is visible
> 
> im not arguing that, im only pointing out that removing cutscenes.rpf does nothing

It does for me: (even with this asi)
https://streamable.com/n1cl70
Set your screen to 60hz for the best result

**Comment by RecklessGlue540** [comment] 2024-01-15 13:43
> with and without said rpf feels absolutely same https://streamable.com/urj6hs https://streamable.com/4c3cum (using asi from this issue)

For the second one, it looks smooth but it looks like 30fps...

**Comment by RecklessGlue540** [comment] 2024-01-15 14:09
> Grand.Theft.Auto.4.2024.01.15.-.21.44.07.06.mp4 
> That's what I see without fixes, and this is what I don't see with asi above.
> 
>  Grand.Theft.Auto.4.2024.01.15.-.21.50.21.07.mp4

That trembling? I'm pretty much talking about the overall cutscene smoothness, tho I've seen that tremble in the intro when the car (schafter) is being lifted, even with this .asi... that's a good section to test on.

**Comment by ThirteenAG** [comment] 2024-01-15 14:24
[GTAIV.EFLC.FusionFix.zip](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/files/13939844/GTAIV.EFLC.FusionFix.zip)

Try with this.

**Comment by RecklessGlue540** [comment] 2024-01-15 14:46
> [GTAIV.EFLC.FusionFix.zip](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/files/13939844/GTAIV.EFLC.FusionFix.zip)
> 
> Try with this.

No difference.
Car still trembles. https://streamable.com/lz865v

**Comment by ThirteenAG** [comment] 2024-01-15 15:02
https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/assets/4904157/1782e028-b92c-435a-ac9b-3c033dbf3648

Not as much for me. But I did restore previous version of cutscene fix for this test, dunno if related.

[GTAIV.EFLC.FusionFix.zip](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/files/13940257/GTAIV.EFLC.FusionFix.zip)

**Comment by RecklessGlue540** [comment] 2024-01-15 15:33
Still no difference...

**Comment by TailsGuy** [comment] 2024-01-15 17:09
I'll try this when I'm home.

**Comment by RecklessGlue540** [comment] 2024-01-15 20:22
> The animation stuttering is a lot less visible at higher framerates for me, so if you play at 60 fps, it would feel a lot worse than if you were constantly holding 120 fps+ during cutscenes (even beyond just the difference between 60 and 120 fps). Capping the game at 60 fps vs 120 fps using FusionFix's framerate limiter shows a massive difference in cutscene smoothness 

This is what I think as well. I think all of these fixes are meant to be used at absurd framerates, which is not preferable, since it's well known the game breaks above even 60.

All the footage ThirteenAG has shown runs at abysmally high framerates. 
That's probably why he doesn't notice differences with or without cutscenes.rpf sound files...
So I guess this is more of an issue at lower framerates like 60 or 30 (just like loading times)...

And, from what I've seen, when you run the cutscenes at 30fps, their smoothness seems to be 20fps-ish...
When running at 60, they seem to be 30fps-ish or so...

**Comment by TessellatedGuy** [comment] 2024-01-15 21:11
> And, from what I've seen, when you run the cutscenes at 30fps, their smoothness seems to be 20fps-ish... When running at 60, they seem to be 30fps-ish or so..

I noticed this as well, and that might explain why 120 fps looks more like "60 fps" in my video, but not quite _"perfect"_ 60 fps. If this hypothesis is true, at 240 fps you'd be getting roughly ~120 fps smoothness but with some stutter. I would guess that since 120 fps is just naturally a very high framerate, you notice less of those stutters, which only happen for a few frames out of 120 frames every second. At 120 fps (with ~60 fps cutscene animations), those "few frames" of stutter would take up a lot more time on screen per second.

This also might mean the stutter happens for a fixed amount of frames, so no matter your framerate, you're only going to stutter/drop 3 frames in a second of an animation (for example). At 30 fps, 3 frames is a _lot,_ but at 120 fps, 3 frames is a drop in the bucket.

Of course, I might be wrong about this, since I can't actually prove it.

**Comment by Undisputed00x** [comment] 2024-01-16 01:26
@TessellatedGuy @RecklessGlue540 

no, still my cutscenes play around 170- 230 fps and comparing to w/o cutscenes.rpf trick the difference is still big, cutscenes again feel playing in like close to 60fps framerate. 
Only w/o cutscenes.rpf there is true visible fluidity in the game's cutscenes on my 144hz display.

**Comment by TessellatedGuy** [comment] 2024-01-16 02:14
> no, still my cutscenes play around 170- 230 fps and comparing to w/o cutscenes.rpf trick the difference is still big, cutscenes again feel playing in like close to 60fps framerate. Only w/o cutscenes.rpf there is true visible fluidity in the game's cutscenes on my 144hz display.

I agree, there is definitely still visible stutter at higher framerates. I was more talking about how much worse the stuttering is at lower framerates and why that may be.

Also, I recorded a clip of that scene with cutscenes.rpf removed, with the same .asi and 60 fps limit as before, and the difference is remarkable:

https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/assets/13260031/251b2feb-8f0d-441f-9f88-4c3423159580

That _finally_ looks like a flawless 60 fps as you'd expect, and smoother than when I tried running that cutscene normally at 165 fps, which is my monitor's max refresh rate.

**Comment by ThirteenAG** [comment] 2024-01-16 03:38
I doubt anything can be done about that until someone finds a code path to disable, that will make cutscenes act like without rpf. I personally barely see a difference (with high fps), and what I've looked for is how to avoid jitter, since I can reproduce it immediately. If it doesn't break anything, I'll include it in the next release. The rest is separate issue.

**Comment by hammerfist11** [comment] 2024-01-16 03:45
All I can say is that for me when playing at a capped 60fps, the cutscenes are noticeable laggy, and it takes away from the experience quite a bit given how story driven the game is. Glad you're working on it, but disappointed that there is still no identified reason in regards to what is causing this given how long it's been an issue.

**Comment by Undisputed00x** [comment] 2024-01-16 13:51
@RecklessGlue540 no difference from me. By capping the game makes it even worse

**Comment by RecklessGlue540** [comment] 2024-01-16 13:57
> The rest is separate issue.

Ahh, I understand now. So the jittering, zooming and stuttering are all separate issues... I see... interesting for sure.

> until someone finds a code path to disable, that will make cutscenes act like without rpf...

Would things really be that easy tho? I doubt it...

Anyway, On a side note, a lot of Rockstar's RAGE games seem to have this "stuttering" issue in cutscenes... Notable examples include RDR1 and GTAV...
Max Payne 3 seems to be free from this, thankfully...

**Comment by HAYASHIDASEIYAKU** [comment] 2024-01-26 14:38
I remember this problem also exists in GTASA.
The police car in the opening animation has a similar shaking problem.

**Comment by RecklessGlue540** [comment] 2024-02-23 22:37
@Undisputed00x, @JackSound01, @TessellatedGuy
Can you guys try out capping the cutscenes through FF at 32fps, 64fps, 128fps and 256fps and see how the smoothness is? Of course with all of these fixes enabled.

On patch 1.0.0.0, cutscenes were hard capped at 32. 
And keep in mind, the cutscene audio files are 32000hz, so that means 32000hz cutscene audio = 32fps for proper sync?

**Comment by Undisputed00x** [comment] 2024-02-24 01:18
@RecklessGlue540 
We've done that in the past and like expected still no improvement either capping frames or not. 
I dunno but there are moments depending the scene when framerate is fluid as it should, also i notice this in the last frames when skipping the cutscenes.

**Comment by RecklessGlue540** [comment] 2024-02-24 01:25
> @RecklessGlue540 We've done that in the past and like expected still issue isnt resolved either by capping the frames or not. I dunno but there are moments depending the scene when framerate is fluid as it should, also i notice this in the last frames when skipping the cutscenes.

Yeah, when cutscenes change sections and during the screen fade ins / outs, they are completely smooth.

**Comment by HAYASHIDASEIYAKU** [comment] 2024-02-25 15:02
The fade-in effect will cause the game to skip frames.
The best place to test this is in the theater. After watching a show with friends, there is a high probability that their first words will be sped up. You can only know this by watching the conversation history.

**Comment by Joris-truly** [comment] 2024-08-05 14:29
Adding to the issue of 'camera judder in cutscenes still being a problem at 60fps': I tried deleting the cutscenes.rpf to see it for myself, and it's staggering how smooth the cutscenes suddenly are. What a mess of spaghetti code this engine must be to create such a problem.

**Comment by Undisputed00x** [comment] 2024-08-10 14:29
This problem hasn't been fixed (although didn't intended to be) in the new 3.0v update.

**Comment by hammerfist11** [comment] 2024-08-10 15:59
> This problem hasn't been fixed (although didn't intended to be) in the new 3.0v update.

sad face

**Comment by JackSound01** [comment] 2024-09-04 03:34
Playing at 120fps and above seems to be very smooth but at 60fps stutters a lot, any fix??

**Comment by Tomasak** [comment] 2024-12-21 10:06
[GTAIV.EFLC.FusionFix.zip](https://github.com/user-attachments/files/18218105/GTAIV.EFLC.FusionFix.zip)
please check this asi

**Comment by RecklessGlue540** [comment] 2024-12-21 12:51
> [GTAIV.EFLC.FusionFix.zip](https://github.com/user-attachments/files/18218105/GTAIV.EFLC.FusionFix.zip) please check this asi

This totally fixes it without any visible or audible downside at any framerate from my testing.

https://github.com/user-attachments/assets/2d561df5-ffca-4f01-9745-efb45f74b1bf

Watch this at 60hz btw.

I didn't check thoroughly, does this fix also fix the zooming all by itself? I have a feeling it might.

**Comment by JackSound01** [comment] 2024-12-21 14:38
> > [GTAIV.EFLC.FusionFix.zip](https://github.com/user-attachments/files/18218105/GTAIV.EFLC.FusionFix.zip) please check this asi
> 
> This totally fixes it without any visible or audible downside at any framerate from my testing.
> 
>  Gtaiv.2024-12-21.14-46-43.mp4 
> Watch this at 60hz btw.
> 
> I didn't check it really that thoroughly, does this fix also fix the zooming all by itself? I have a feeling it might.

Cutscenes seems to be fix, but in gameplay the game sttuters a lot, it's unplayable sadly..

**Comment by RecklessGlue540** [comment] 2024-12-21 15:01
> > > [GTAIV.EFLC.FusionFix.zip](https://github.com/user-attachments/files/18218105/GTAIV.EFLC.FusionFix.zip) please check this asi
> > 
> > 
> > This totally fixes it without any visible or audible downside at any framerate from my testing.
> > Gtaiv.2024-12-21.14-46-43.mp4
> > Watch this at 60hz btw.
> > I didn't check it really that thoroughly, does this fix also fix the zooming all by itself? I have a feeling it might.
> 
> Cutscenes seems to be fix, but in gameplay the game sttuters a lot, it's unplayable sadly..

I couldn't spot a single stutter in gameplay personally...
Are you sure this is even related to this .asi?

**Comment by JackSound01** [comment] 2024-12-21 15:28
> > > > [GTAIV.EFLC.FusionFix.zip](https://github.com/user-attachments/files/18218105/GTAIV.EFLC.FusionFix.zip) please check this asi
> > > 
> > > 
> > > This totally fixes it without any visible or audible downside at any framerate from my testing.
> > > Gtaiv.2024-12-21.14-46-43.mp4
> > > Watch this at 60hz btw.
> > > I didn't check it really that thoroughly, does this fix also fix the zooming all by itself? I have a feeling it might.
> > 
> > 
> > Cutscenes seems to be fix, but in gameplay the game sttuters a lot, it's unplayable sadly..
> 
> I couldn't spot a single stutter in gameplay personally... Are you sure this is even related to this .asi?

100% sure, i put back the original file and my game has 60fps stable..

**Comment by TessellatedGuy** [comment] 2024-12-21 15:42
> [GTAIV.EFLC.FusionFix.zip](https://github.com/user-attachments/files/18218105/GTAIV.EFLC.FusionFix.zip) please check this asi

I can also confirm that this fixes the cutscene stutter. They look completely smooth now at 60 fps. Didn't notice any downsides, gameplay was smooth too. I only have FusionFix and DXVK installed, no other mods.

**Comment by ThirteenAG** [comment] 2024-12-21 16:39
> > > [GTAIV.EFLC.FusionFix.zip](https://github.com/user-attachments/files/18218105/GTAIV.EFLC.FusionFix.zip) please check this asi
> > 
> > 
> > This totally fixes it without any visible or audible downside at any framerate from my testing.
> > Gtaiv.2024-12-21.14-46-43.mp4
> > Watch this at 60hz btw.
> > I didn't check it really that thoroughly, does this fix also fix the zooming all by itself? I have a feeling it might.
> 
> Cutscenes seems to be fix, but in gameplay the game sttuters a lot, it's unplayable sadly..

The code patched in this build only runs in cutscenes, there's 0% chance it affects anything during gameplay.

**Comment by JackSound01** [comment] 2024-12-21 16:51
> > > > [GTAIV.EFLC.FusionFix.zip](https://github.com/user-attachments/files/18218105/GTAIV.EFLC.FusionFix.zip) please check this asi
> > > 
> > > 
> > > This totally fixes it without any visible or audible downside at any framerate from my testing.
> > > Gtaiv.2024-12-21.14-46-43.mp4
> > > Watch this at 60hz btw.
> > > I didn't check it really that thoroughly, does this fix also fix the zooming all by itself? I have a feeling it might.
> > 
> > 
> > Cutscenes seems to be fix, but in gameplay the game sttuters a lot, it's unplayable sadly..
> 
> The code patched in this build only runs in cutscenes, there's 0% chance it affects anything during gameplay.

Very strange then, i put it on plugins folder, and i only have dxvk 5.2, fusion fix, various fixes, and a commandline (-percentvidmem 0,-norestrictions, -availablevidmem 4096, -framelimit 0,-nomemrestrict)

**Comment by Undisputed00x** [comment] 2024-12-21 17:10
> [GTAIV.EFLC.FusionFix.zip](https://github.com/user-attachments/files/18218105/GTAIV.EFLC.FusionFix.zip) please check this asi

Wow! 🚀🚀
Finally, I can confirm that the problem is fixed for me as well. Now 60+ fps cutscenes look really fluid.

**Comment by ThirteenAG** [comment] 2024-12-21 17:15
Please test more thoroughly if you can, if indeed all good, we'll make a new release in the near future.

**Comment by Tomasak** [comment] 2024-12-22 09:39
> > > > > [GTAIV.EFLC.FusionFix.zip](https://github.com/user-attachments/files/18218105/GTAIV.EFLC.FusionFix.zip) please check this asi
> > > > 
> > > > 
> > > > This totally fixes it without any visible or audible downside at any framerate from my testing.
> > > > Gtaiv.2024-12-21.14-46-43.mp4
> > > > Watch this at 60hz btw.
> > > > I didn't check it really that thoroughly, does this fix also fix the zooming all by itself? I have a feeling it might.
> > > 
> > > 
> > > Cutscenes seems to be fix, but in gameplay the game sttuters a lot, it's unplayable sadly..
> > 
> > 
> > The code patched in this build only runs in cutscenes, there's 0% chance it affects anything during gameplay.
> 
> Fix it, now is working fine with dxvk 2.5.2, commandline (-percentvidmem 0,-norestrictions, -availablevidmem 4096, -framelimit 0,-nomemrestrict), but i noticed that if i start a new game in TBoGT the game crash, not happens when i'm in a gta iv session and start a new game of TBoGT..

you only should use command -availablevidmem (YOUR VRAM IN MB) and nothing else.

**Comment by JackSound01** [comment] 2024-12-22 12:53
> > > > > > [GTAIV.EFLC.FusionFix.zip](https://github.com/user-attachments/files/18218105/GTAIV.EFLC.FusionFix.zip) please check this asi
> > > > > 
> > > > > 
> > > > > This totally fixes it without any visible or audible downside at any framerate from my testing.
> > > > > Gtaiv.2024-12-21.14-46-43.mp4
> > > > > Watch this at 60hz btw.
> > > > > I didn't check it really that thoroughly, does this fix also fix the zooming all by itself? I have a feeling it might.
> > > > 
> > > > 
> > > > Cutscenes seems to be fix, but in gameplay the game sttuters a lot, it's unplayable sadly..
> > > 
> > > 
> > > The code patched in this build only runs in cutscenes, there's 0% chance it affects anything during gameplay.
> > 
> > 
> > Fix it, now is working fine with dxvk 2.5.2, commandline (-percentvidmem 0,-norestrictions, -availablevidmem 4096, -framelimit 0,-nomemrestrict), but i noticed that if i start a new game in TBoGT the game crash, not happens when i'm in a gta iv session and start a new game of TBoGT..
> 
> you only should use command -availablevidmem (YOUR VRAM IN MB) and nothing else.

Ok thanks man!!, Trying yesteday i noticed that my game after a few minutes of free roam sttuters a lot, thing that not happend a few months before, any help?

**Closed** 2024-12-22 13:15 UTC
