### ISSUE TITLE
Blow Your Cover - Bugged Mission

### ISSUE THREAD

**Issue by NoelCosta** [ThirteenAG/GTAIV.EFLC.FusionFix#311] opened 2023-12-13 01:51 UTC
I tried everything, fusion 2.0, 2.1 & 2.2, Vanilla, Downgrading the save file, Alt Dialog On & Off, updating graphics drivers - Nvidia, restarting my game and PC, 30fps lock, I don't know what else to try.

I even tried a trainer as suggested in another post, which when teleporting to another location the cops last longer, but as soon as I loose the cops, the mission abruptly ends and he turns into a normal npc.

To provide more context, I started my game with 2.2 on the latest patch of the complete edition.

**Comment by ThirteenAG** [comment] 2023-12-13 03:48
v2.1 bug was happening before losing the cops though. Can you put v2.1 asi, set alt. dialogues to on and see if it changes anything?

**Comment by NoelCosta** [comment] 2023-12-13 13:28
Just tried it again with a fresh install of GTA 4,and 2.1, with Alt Dialog turned on, and I still instantly lose the cops and turns into an NPC abruptly.

I also tried an earlier save on my steam deck (fresh install) before Dimitri betrays you and burns your safehouse, but the same bug occurs.

I have seen other posts say that this is an issue with a variable changed on the save itself, if this is true, is it possible to identify the variable and change it manually? I really do not want to start a new save.

**Comment by ThirteenAG** [comment] 2023-12-13 13:32
That's different issue then, since you've said you started the game with 2.2, you shouldn't be affected. Can you send over the save file?

**Comment by NoelCosta** [comment] 2023-12-13 13:35
sure, here is my recent save file
[SGTA405.zip](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/files/13661248/SGTA405.zip)

**Comment by ThirteenAG** [comment] 2023-12-13 14:05
Is it possible that you had a save game made with v2.1, then you upgraded to v2.2, loaded that save, and started a new game?

Because I've checked, and the variable responsible for making this mission fail, is still the same as previous issue, but it's not affected by fusion fix 2.2. So it's strange something corrupted it again.

Here's how you can try to salvage that save:
[GTAIV.EFLC.FusionFix.zip](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/files/13661515/GTAIV.EFLC.FusionFix.zip)
Load it with this asi, resave.
Replace asi with v2.2, then resave again, and try to pass the mission.

**Comment by NoelCosta** [comment] 2023-12-13 14:08
I'll try that now, thanks :)

**Comment by NoelCosta** [comment] 2023-12-13 14:30
![image](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/assets/93773103/82d059b3-559f-48b2-b2b5-ae1b78180b31)

So, I managed to lose the cops and the mission did not fail, now I have to drive him back, but he is staying in this position.

**Comment by ThirteenAG** [comment] 2023-12-13 14:37
I don't know then. Can you answer this?

> Is it possible that you had a save game made with v2.1, then you upgraded to v2.2, loaded that save, and started a new game?

**Comment by NoelCosta** [comment] 2023-12-13 14:40
[test.zip](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/files/13661900/test.zip)

As far as I remember I started with 2.2, these are the original files from when I started my 1st playthrough

**Comment by NoelCosta** [comment] 2023-12-13 14:48
Update:

Even though Playboy was still stuck on top of the roof I fixed the issue by grabbing a taxi nearby him, then as soon as I set off to the destination I skipped the journey, and both Playboy and I got off the cab together.

Given what happened now, do you recommend playing on 2.1 or 2.2? Also should I have Alt dialogue on or off?

**Comment by ThirteenAG** [comment] 2023-12-13 14:51
Well, code wise this should not have happened with 2.2.
Alt dialogue off acts just like original game, so the choice is up to you.

**Comment by NoelCosta** [comment] 2023-12-13 15:07
Excellent, Thank you so much :)

**Comment by NoelCosta** [comment] 2023-12-13 15:32
@ThirteenAG Not sure if this helps, but maybe the combination of both these mods caused the issue?

https://www.nexusmods.com/gta4/mods/234?tab=posts&BH=0

Its a radio mod

**Comment by ThirteenAG** [comment] 2023-12-13 15:35
I don't know. Would be good if you tried to remove your saves temporarily, start new game with v2.2 and check if this bug still happens.

**Comment by ThirteenAG** [comment] 2023-12-13 15:43
Leave open, in case someone else can confirm or deny that the bug still happens.

**Comment by ThirteenAG** [comment] 2023-12-13 16:15
For what it's worth, I tried to launch new game without any saves, load this mission with mission loader, and the bug is not reproducible that way.

**Comment by NoelCosta** [comment] 2023-12-13 20:36
I think I figured it out, I might have not actually been using 2.2 for the first time.

The Radio mod had its own fusionfix files, and I imported them after I imported fusionfix 2.2, so maybe the files where overwritten to an older version.

Either way these steps you mentioned earlier fixed the issue:

Here's how you can try to salvage that save:
[GTAIV.EFLC.FusionFix.zip](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/files/13661515/GTAIV.EFLC.FusionFix.zip)
Load it with this asi, resave.
Replace asi with v2.2, then resave again, and try to pass the mission.

**Comment by ThirteenAG** [comment] 2023-12-14 02:11
That would make sense, you can close this then.

**Closed** 2023-12-14 12:33 UTC

**Comment by ZenomeFR** [comment] 2023-12-19 20:27
Hi, I have the same issue, tried multiple time and everytime Playboy become an NPC with the 2 stars police appears.
I tried to replace the .asi file you gave earlier then load the game and save, re-change with the latest version, load and save. But I can pass it...
Can you help please ?

Thanks a lot :)

**Comment by ThirteenAG** [comment] 2023-12-20 03:54
Solution above is all I can do, unfortunately.
