### ISSUE TITLE
Game crash GTAIV.EFLC.FusionFix v2.2

### ISSUE THREAD

**Issue by PekM** [ThirteenAG/GTAIV.EFLC.FusionFix#313] opened 2023-12-13 11:23 UTC
I've just installed this mod on a clean gta 4 installation and the game crash instantly

I've tried to run the game in -windowed mode

i've tried to run the fix with DXVK and without DXVK
Without DXVK
[GTAIV.exe.20231213112022.dmp](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/files/13660047/GTAIV.exe.20231213112022.dmp)
[GTAIV.exe.20231213112022.log](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/files/13660048/GTAIV.exe.20231213112022.log)

With DXVK
[GTAIV.exe.20231213111207.log](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/files/13660066/GTAIV.exe.20231213111207.log)
[GTAIV.exe.20231213111207.zip](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/files/13660087/GTAIV.exe.20231213111207.zip)

**Comment by ThirteenAG** [comment] 2023-12-13 11:52
Your first dump is RGL crash, that happens every other launch without any mods.
Second one I'm not sure. Does it happen on every launch?

**Comment by ThirteenAG** [comment] 2023-12-13 12:04
[GTAIV.EFLC.FusionFix.zip](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/files/13660430/GTAIV.EFLC.FusionFix.zip)
If it's indeed native related, then this build should help.

**Comment by PekM** [comment] 2023-12-13 13:32
> Your first dump is RGL crash, that happens every other launch without any mods. Second one I'm not sure. Does it happen on every launch?

For the second one yeah it happen everytime.

The .asi you just provided fix the crash my game now start with or WIthout DXVK when fusion fix is installed

**Comment by ThirteenAG** [comment] 2023-12-13 13:33
Okay, good to know, will be included in the next release then.

**Comment by YoItsKelz** [comment] 2023-12-17 19:19
I'm having the same issue. How do I get the crash log?

**Comment by RecklessGlue540** [comment] 2023-12-17 19:26
> I'm having the same issue. How do I get the crash log?

Create CrashDumps folder in IV's directory. Reproduce the crash, upload it somewhere and link here.

**Comment by PekM** [comment] 2023-12-17 21:35
> I'm having the same issue. How do I get the crash log?

Did you tried the fix Thirteen Provided ?
https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/issues/313#issuecomment-1853793177

**Comment by YoItsKelz** [comment] 2023-12-17 21:51
> > I'm having the same issue. How do I get the crash log?
> 
> Create CrashDumps folder in IV's directory. Reproduce the crash, upload it somewhere and link here.



> > I'm having the same issue. How do I get the crash log?
> 
> Did you tried the fix Thirteen Provided ? [#313 (comment)](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/issues/313#issuecomment-1853793177)

I re-downloaded and re-copied the files and restarted the computer. This time it got through to the game without issues. I don't have a log because it worked, but it must have been something going on locally. If the fix Thirteen provided was in the latest download, that may have been it. TY!

**Comment by ThirteenAG** [comment] 2023-12-18 04:31
It's not latest yet, will be released today.

**Comment by Tomasak** [comment] 2023-12-25 16:22
2.3.1 was released to fix crashing on startup for some people. please try and report if its fixed, or upload crashdump if issue persists.

**Closed** 2023-12-25 17:07 UTC
