### ISSUE TITLE
Game doesn't load regardless if I launch it from Steam or from RGL

### ISSUE THREAD

**Issue by honest4life** [ThirteenAG/GTAIV.EFLC.FusionFix#275] opened 2023-11-26 09:19 UTC
Ever since I installed v2.1 of Fusion Fix, game is stuck on an endless loop trying to launch and after a few seconds, RGL will say "A game is currently running - Grand Theft Auto IV is currently running. By choosing to exit, Grand Theft Auto IV will be quit and any unsaved progress will be lost".

![RGL problem](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/assets/147522862/13436ffe-cbf7-45a3-912a-a5f849c8ea11)

I also tried removing every other mod and installing only FusionFix to see if it is really a fusion fix issue or it is in conflict with some other mod. Again, the same result:
![Screenshot_12](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/assets/147522862/8add9bee-82b6-461b-837a-d4212cbeb56d)

Now, upon discovering, I checked the "CrashDumps" folder that I created in the root folder of GTA IV. I then noticed some files, which never appeared before because the game was loading up just fine with zero issues. I will add what I encountered in case if it is of any help:

[GTAIV.exe.20231125204846.dmp](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/files/13466348/GTAIV.exe.20231125204846.dmp)
[GTAIV.exe.20231125204846.log](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/files/13466349/GTAIV.exe.20231125204846.log)

**Comment by honest4life** [comment] 2023-11-26 09:26
I reverted back to v2.0 of Fusion Fix and the game loads up as it should. Only Fusion Fix was installed, no other mod was installed

**Comment by honest4life** [comment] 2023-11-26 09:30
I also forgot to mention, this was tested on version 1.2.0.5.9. of GTA IV Complete Edition. No downgrades or anything like that 
![Screenshot_13](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/assets/147522862/6f9a1a6f-5db7-4510-ba04-b7624d774ae8)

**Comment by ThirteenAG** [comment] 2023-11-26 10:29
Your crash dump looks like a crash that happens when RGL fails to launch the game for some reason. It happens even without any mods, randomly. Usually when fusion fix crashes, it's shown in the dump. Are you sure 2.1 doesn't work? It's not much different from 2.0, I see no reason for it to crash like that.

**Comment by honest4life** [comment] 2023-11-26 11:52
A couple of hours later, I noticed FusionFix was updated again, 6 hours ago at the time I am writing this comment. Anyway, I decided to download the latest version again and this time, with nothing else besides FusionFix. Here are a couple of screenshots showcasing the error, as well as the date of the file FusionFix.asi file, in case it helps you. Oddly enough, now I didn't get any crashdumps in folder. And you also have a screenshot of my game's root folder to see if it is something there that it is installed oddly:


![Screenshot_15](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/assets/147522862/82e0267d-d22e-4c9f-bb97-fd2beb9cb44a)
![Screenshot_16](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/assets/147522862/8f63ca26-42f1-4451-8764-5ca35b8d2704)
![Screenshot_17](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/assets/147522862/9daa9476-352e-4006-97f5-92a0b5d6bbbe)

**Comment by ThirteenAG** [comment] 2023-11-26 12:06
Go to task manager and kill gtaiv.exe process. Perhaps it's just stuck.

**Comment by honest4life** [comment] 2023-11-26 13:00
I just did that. Still the same.

I even tried a PC restart and even uninstalling and reinstalling the game through Steam. Same result. 

Here is a link with me using OBS in case it helps you what it is wrong: https://streamable.com/j164px

I also got two more crashdumps:

[GTAIV.exe.20231126144654.log](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/files/13466806/GTAIV.exe.20231126144654.log)
[Uploading GTAIV.exe.20231126143239.dmp…]()

**Comment by ThirteenAG** [comment] 2023-11-26 13:05
I can't reproduce this, also tried to install clean steam version.
When fusion fix crashes, your log should say something like:
`Unhandled exception at 0x6BEBED5F in GTAIV.EFLC.FusionFix.asi (+0x3ed5f): 0xC0000005: Access violation reading location 0x00000000.`
Instead what you have: 
`Unhandled exception at 0x72A416AD in GTAIV.exe: 0xC0000005: Access violation DEP at 0x72A416AD.`
That could be pretty much anything.
You have extra files in your directory, like what appears to be dxvk, and other plugins, try without them. If you're doing a fresh install, make sure those files are removed from directory before installation.

**Comment by ThirteenAG** [comment] 2023-11-26 13:13
Also you have two asi loaders, dinput8.dll and dsound.dll, normally it shouldn't be a problem, but since you have project 2dfx, and it's rather old, it's loaded twice because it doesn't have a check to prevent that and crashes.

**Comment by honest4life** [comment] 2023-11-26 14:03
ok, this time, I removed some of the files, including something like the GTAIV.exe and other essentials (just to make sure) and then I went to Steam and clicked on "Verify Integrity of game files". Once I clicked on it, the vanilla files reinstalled back. I then tried to launch the Complete Edition normally without mods and it worked and then I installed FusionFix 2.1. update and this time, it actually run. I only got the error with "Not being signed in on Social Club", but it is irrelevant as I got to the game. 

Link: https://streamable.com/z9p3gp


Should I insert inside the plugins/GTAIV.EFLC.FusionFix.ini an argument like "SkipIntro = 0" ; "SkipMenu = 0"? I like the GTA IV intro and menu screens.

**Comment by honest4life** [comment] 2023-11-26 14:11
also tried installing a new version of Project2DFX, which is the 4.5 and still the game loaded up. So, I guess, Project2DFX isn't to blame here either

**Comment by ThirteenAG** [comment] 2023-11-26 14:58
Well, maybe dsound somehow caused another thing that prevented you from launching the game. 
You don't need to edit ini for menu options now, just change them via in-game menu.

**Comment by ThirteenAG** [comment] 2023-11-26 15:01
Social club message means that social club is still loading, not my fault it's too slow for no reason at all. Once it's loaded, game proceeds automatically.

**Comment by ThirteenAG** [comment] 2023-11-26 15:03
Alright, closing.

**Closed by ThirteenAG** 2023-11-26 15:03 UTC
