### ISSUE TITLE
Couple issues with latest fusionfix version

### ISSUE THREAD

**Issue by MOnkeMan5009** [ThirteenAG/GTAIV.EFLC.FusionFix#654] opened 2024-11-04 23:32 UTC
### Game version this happens in

v1.2.0.59

### What area of the game

Throughout the city, as shown in recording.

https://github.com/user-attachments/assets/cdcaed94-4d48-4c13-88ac-db90ef7cca0a

https://github.com/user-attachments/assets/008b4e74-a1a9-4d9c-a4e0-8bb8573c8dee

### What should happen

Some parts seem to have problems with loading LODs, some flickering on tree leaves here and there ( which were not present in 2.5.6, my last used version before this ) and some shadow flickering.
mod seems almost perfect, just a few things
[New game has also been started to avoid any save bugs]

### Last working version

v2.5.6

### Checklist

- [X] Test in the [latest git build](https://ci.appveyor.com/api/projects/ThirteenAG/gtaiv-eflc-fusionfix/artifacts/GTAIV.EFLC.FusionFix.zip) in case it's already fixed.
- [X] [Search for other reports](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/search?q=my+issue&type=issues) of the same issue.
- [X] Include logs or screenshots of issue.

**Comment by cpmodding** [comment] 2024-11-06 12:08
Problem occurs in lodcull_e.wpl file, which forces to show lower LOD models in certain areas.

**Comment by MOnkeMan5009** [comment] 2024-11-06 19:02
> Problem occurs in lodcull_e.wpl file, which forces to show lower LOD models in certain areas.

its been fixed? also shadows too

**Comment by Parallellines0451** [comment] 2024-11-06 21:38
1. Enable HighResolutionShadows in the ini.
2. Map issue, out of scope for FF.

**Closed** 2024-11-07 05:14 UTC

**Comment by MOnkeMan5009** [comment] 2024-11-07 14:45
> 1. Enable HighResolutionShadows in the ini.
> 2. Map issue, out of scope for FF.

about the 2nd thing, this did not happen on fusionfix 2.5.6

**Comment by MOnkeMan5009** [comment] 2024-11-08 23:24
> 1. Enable HighResolutionShadows in the ini.
> 2. Map issue, out of scope for FF.

did a complete new reinstallation with just FF installed. this is definitely a FF issue. this did not happen before

**Comment by Parallellines0451** [comment] 2024-11-09 02:37
> about the 2nd thing, this did not happen on fusionfix 2.5.6
> this is definitely a FF issue. this did not happen before

Wrong. Here's vanilla:

![GTAIV_2024_11_07_22_05_33_752](https://github.com/user-attachments/assets/6458533a-e7d7-4d84-8d56-609280341190)

Please refrain from opening issues if you won't bother to do the bare minimum and actually check if a bug is caused by the mod.

**Comment by MOnkeMan5009** [comment] 2024-11-10 11:09
> > about the 2nd thing, this did not happen on fusionfix 2.5.6
> > this is definitely a FF issue. this did not happen before
> 
> Wrong. Here's vanilla:
> 
> ![GTAIV_2024_11_07_22_05_33_752](https://private-user-images.githubusercontent.com/133058741/384566606-6458533a-e7d7-4d84-8d56-609280341190.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEyMzcyMzksIm5iZiI6MTczMTIzNjkzOSwicGF0aCI6Ii8xMzMwNTg3NDEvMzg0NTY2NjA2LTY0NTg1MzNhLWU3ZDctNGQ4NC04ZDU2LTYwOTI4MDM0MTE5MC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExMFQxMTA4NTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kODgxZGVkN2VmMTc2NmZkMjU0ZDNkOTdiNzY1NzdhZTFlZjkxMjAyYTZiNzkzNjQ0M2QyODgyOTNkNDI2NDhiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.ZVqnpKNvIL5zOXeh5V8F7Nv6Z6QdXIAfcwfQQwBOGfo)
> 
> Please refrain from opening issues if you won't bother to do the bare minimum and actually check if a bug is caused by the mod.

Do you know at least if its possible for next upcoming FF versions to improve this stuff?
