### ISSUE TITLE
game doesnt start

### ISSUE THREAD

**Issue by valoplayer** [ThirteenAG/GTAIV.EFLC.FusionFix#292] opened 2023-12-04 17:48 UTC
The game doesnt start but runs as a background process not sure what to do when i remove the files it seems to be working alright

**Comment by BlancX10** [comment] 2023-12-05 18:09
I have the same problem. Version 2.1 has this issue. Use 2.0 in the meantime.

**Comment by Laksh2007** [comment] 2023-12-05 20:22
Even v2.0 is not safe. It has the same issue. If you're using either Patch 7 or Patch 8 use Fusion Fix v1.96 as there at least the game does run.

**Comment by ThirteenAG** [comment] 2023-12-06 06:10
Nothing I can do without a crash dump.

**Comment by Tomasak** [comment] 2023-12-25 16:21
2.3.1 was released to fix crashing on startup for some people. please try and report if its fixed, or upload crashdump if issue persists.

**Comment by BlancX10** [comment] 2023-12-25 19:27
> 2.3.1 was released to fix crashing on startup for some people. please try and report if its fixed, or upload crashdump if issue persists.

It's fixed. No problem when I started the game. Thanks.

**Comment by Laksh2007** [comment] 2023-12-25 20:36
The issue is now fixed on my side too. Thank you for the help!

**Closed** 2023-12-26 10:01 UTC
